Project2/WholeProject/basePackage/main/default/objects/Auction__c/Auction__c.object-meta.xml
<CustomObject>
    <label>Auction</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Auction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project2/force-app/main/default/objects/Auction__c/fields/Minimum_Bid__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Bid__c</fullName>
    <label>Minimum Bid</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Project2/force-app/main/default/objects/Bid__c/Bid__c.object-meta.xml
<CustomObject>
    <label>Bid</label>
    <nameField>
        <displayFormat>BID-{0000}</displayFormat>
        <label>Bid ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project2/force-app/main/default/objects/Bid__c/fields/Auction__c.field-meta.xml
<CustomField>
    <fullName>Auction__c</fullName>
    <label>Auction</label>
    <referenceTo>Auction__c</referenceTo>
    <relationshipLabel>Bids</relationshipLabel>
    <relationshipName>Bids</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project2/basePackage/main/default/objects/Bid__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Project2/WholeProject/UsersPackage/main/default/classes/BidTriggerHandler.cls
public class BidTriggerHandler {

    public static void validate(List<Bid__c> bids) {
        // Reject all bids if multiple bids are being inserted
        if (bids.size() > 1) {
            for (Bid__c bid : bids) {
                bid.addError('Cannot add more than one bid at a time.');
            }
            return;
        }
        
        // Assign single bid to a variable
        Bid__c bid = bids[0];

        // Reject if bid.Price__c is lower than Max(Price__c) on parent auction
        // Reject if bid.Price__ is lower than Starting Price on parent auction
        Bid__c maxBid;
        Auction__c auction;
        try {
            maxBid = [SELECT Price__c FROM Bid__c WHERE Auction__c=:bid.Auction__c ORDER BY Price__c DESC LIMIT 1];
            if (bid.Price__c <= maxBid.Price__c) {
                bid.addError(
                    String.format(
                        'New bid amount ({0}) cannot be lower than the maximum bid amount ({1}).',
                        new List<Object>{bid.Price__c, maxBid.Price__c}
                    )
                );
            }
        } catch (Exception e) {
            auction = [SELECT Minimum_Bid__c FROM Auction__c WHERE Id =: bid.Auction__c];
            if(bid.Price__c <= auction.Minimum_Bid__c) {
                bid.addError(
                    String.format(
                        'New bid amount ({0}) cannot be lower than the starting bid amount ({1}).',
                        new List<Object>{bid.Price__c, auction.Minimum_Bid__c}
                    )
                );
            }
        }
        
        // Update parent auction, if less than one hour remaining until End_Date__c on time of insert, move End_Date__c to one hour from NOW()
        Auction__c parentAuction = [SELECT End_Date__c FROM Auction__c WHERE Id=:bid.Auction__c];
        
        if(parentAuction.End_Date__c != null) {
            Datetime bidDateTime = Datetime.now();
            Datetime auctionEndDateTime = parentAuction.End_Date__c;
            Long bidTime = bidDateTime.getTime();
            Long auctionEndTime = auctionEndDateTime.getTime();
            Decimal ms = (Decimal) bidTime-auctionEndTime;
            Decimal hr = ms/1000/60/60;
            if ( ms <= 1.0 ) {
                parentAuction.End_Date__c = bidDateTime.addHours(1);
                update parentAuction;
            }
        }
    }
    
}