Project2/WholeProject/basePackage/main/default/objects/Auction__c/Auction__c.object-meta.xml
<CustomObject>
    <label>Auction</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Auction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project2/basePackage/main/default/objects/Auction__c/fields/Auction_Title__c.field-meta.xml
<CustomField>
    <fullName>Auction_Title__c</fullName>
    <label>Auction Title</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project2/WholeProject/basePackage/main/default/objects/Auction__c/fields/Product_Tags__c.field-meta.xml
<CustomField>
    <fullName>Product_Tags__c</fullName>
    <label>Product Tags</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tags</valueSetName>
    </valueSet>
</CustomField>

Project2/force-app/main/default/objects/Bid__c/Bid__c.object-meta.xml
<CustomObject>
    <label>Bid</label>
    <nameField>
        <displayFormat>BID-{0000}</displayFormat>
        <label>Bid ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project2/force-app/main/default/objects/Bid__c/fields/Auction__c.field-meta.xml
<CustomField>
    <fullName>Auction__c</fullName>
    <label>Auction</label>
    <referenceTo>Auction__c</referenceTo>
    <relationshipLabel>Bids</relationshipLabel>
    <relationshipName>Bids</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project2/basePackage/main/default/objects/Bid__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bids</relationshipLabel>
    <relationshipName>Bids</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project2/basePackage/main/default/objects/Bid__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Project2/basePackage/main/default/globalValueSets/Tags.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>Toys &amp; Games</fullName>
    </customValue>
    <customValue>
        <fullName>Art</fullName>
    </customValue>
    <customValue>
        <fullName>Sporting Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Music</fullName>
    </customValue>
    <customValue>
        <fullName>Clothing</fullName>
    </customValue>
    <masterLabel>Tags</masterLabel>
</GlobalValueSet>

Project2/WholeProject/homePage/main/default/classes/featuredSearchHelperTest.cls
@isTest
public with sharing class featuredSearchHelperTest {
    @isTest static void testSearch(){
        Contact testContact = new Contact();
        testContact.Birthdate = Date.newInstance(System.today().year()-20, system.today().month(), system.today().day());
        testContact.LastName = 'bob';
    	List<Auction__c> testAuction = new List<Auction__c>();
        Auction__c valid = new Auction__c();
        
        for(integer x = 7; x > 0; x--){
            Auction__c auc = new Auction__C();
            String name = 'Auction '+x;
            auc.Auction_Title__c = name;
            String elec = 'Electronics';
            auc.Product_Tags__c = elec;
            insert auc;
            
            for(integer y = x; y > 0; y--){
                Bid__c testBid = new Bid__c();
                testBid.Contact__c = testContact.Id;
                testBid.Auction__c = auc.Id;
                testBid.Price__c = 10*x;
            }
            
            testAuction.add(auc);
            if(x == 7){
                valid = auc;
            }
            
        }
        List<Auction__c> response = featuredSearchHelper.getAuctionList('Electronics');
        System.debug(response.size());
        System.assertEquals(response[0], valid);
    }
}