Project2/WholeProject/basePackage/main/default/objects/Auction__c/Auction__c.object-meta.xml
<CustomObject>
    <label>Auction</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Auction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project2/basePackage/main/default/objects/Auction__c/fields/Auction_Title__c.field-meta.xml
<CustomField>
    <fullName>Auction_Title__c</fullName>
    <label>Auction Title</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project2/basePackage/main/default/objects/Auction__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mint</fullName>
            </value>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Poor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project2/WholeProject/basePackage/main/default/objects/Auction__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <label>Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

Project2/force-app/main/default/objects/Auction__c/fields/Minimum_Bid__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Bid__c</fullName>
    <label>Minimum Bid</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Project2/WholeProject/basePackage/main/default/objects/Auction__c/fields/Product_Tags__c.field-meta.xml
<CustomField>
    <fullName>Product_Tags__c</fullName>
    <label>Product Tags</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tags</valueSetName>
    </valueSet>
</CustomField>

Project2/force-app/main/default/objects/Auction__c/fields/Shipping_Cost__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Cost__c</fullName>
    <label>Shipping Cost</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Project2/basePackage/main/default/globalValueSets/Tags.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>Toys &amp; Games</fullName>
    </customValue>
    <customValue>
        <fullName>Art</fullName>
    </customValue>
    <customValue>
        <fullName>Sporting Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Music</fullName>
    </customValue>
    <customValue>
        <fullName>Clothing</fullName>
    </customValue>
    <masterLabel>Tags</masterLabel>
</GlobalValueSet>

Project2/WholeProject/searchResultsPage/main/default/classes/searchResultsPageController.cls
public with sharing class searchResultsPageController {

    @AuraEnabled (Cacheable = true)
    public static List<Auction__c> getSearchResults(String searchTerm){
        String newSearchText = '%' + searchTerm + '%';
        return [SELECT Name, Auction_Title__c, Condition__c, Description__c, Image__c, Minimum_Bid__c, Shipping_Cost__c, Product_Tags__c
                FROM Auction__c WHERE Auction_Title__c LIKE :newSearchText];
    }
}