Project2/WholeProject/basePackage/main/default/objects/Auction__c/Auction__c.object-meta.xml
<CustomObject>
    <label>Auction</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Auction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project2/basePackage/main/default/objects/Auction__c/fields/Auction_Title__c.field-meta.xml
<CustomField>
    <fullName>Auction_Title__c</fullName>
    <label>Auction Title</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project2/WholeProject/searchResultsPage/main/default/classes/searchResultsPageControllerTest.cls
@isTest
public class searchResultsPageControllerTest {

    @isTest
    public static void getSearchResultsTest(){

        for(Integer i = 0; i < 5; i++) {
            if(i < 3) {
                Auction__c newAuction = new Auction__c();
                newAuction.Auction_Title__c = 'Pokemon' + i;
                insert newAuction;
            } else {
                Auction__c newAuction = new Auction__c();
                newAuction.Auction_Title__c = 'YuGiOh' + i;
                insert newAuction;
            }
        }

        List<Auction__c> pokemonAuctions = searchResultsPageController.getSearchResults('Pokemon');
        List<Auction__c> yugiohAuctions = searchResultsPageController.getSearchResults('YuGiOh');

        System.assertEquals(3, pokemonAuctions.size());
        System.assertEquals(2, yugiohAuctions.size());
    }
}