Project2/WholeProject/basePackage/main/default/objects/Auction__c/Auction__c.object-meta.xml
<CustomObject>
    <label>Auction</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Auction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project2/basePackage/main/default/objects/Auction__c/fields/Auction_Title__c.field-meta.xml
<CustomField>
    <fullName>Auction_Title__c</fullName>
    <label>Auction Title</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project2/basePackage/main/default/objects/Auction__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mint</fullName>
            </value>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Poor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project2/force-app/main/default/objects/Auction__c/fields/Minimum_Bid__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Bid__c</fullName>
    <label>Minimum Bid</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Project2/force-app/main/default/objects/Bid__c/Bid__c.object-meta.xml
<CustomObject>
    <label>Bid</label>
    <nameField>
        <displayFormat>BID-{0000}</displayFormat>
        <label>Bid ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project2/force-app/main/default/objects/Bid__c/fields/Auction__c.field-meta.xml
<CustomField>
    <fullName>Auction__c</fullName>
    <label>Auction</label>
    <referenceTo>Auction__c</referenceTo>
    <relationshipLabel>Bids</relationshipLabel>
    <relationshipName>Bids</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project2/basePackage/main/default/objects/Bid__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bids</relationshipLabel>
    <relationshipName>Bids</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project2/basePackage/main/default/objects/Bid__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Project2/WholeProject/BidHistory/main/default/classes/BidHistoryControllerTest.cls
@isTest
public class BidHistoryControllerTest {
    @isTest
    public static void getResultsTest() {
        Auction__c newAuction = new Auction__c();
        Contact newContact = new Contact();
        List<Bid__c> bidInsertList = new List<Bid__c>();
        
        newAuction.Auction_Title__c = 'Test Auction';
        newAuction.Minimum_Bid__c = 5;
        newAuction.Condition__c = 'Mint';
        newContact.LastName = 'Smith';
        newContact.Birthdate = Date.newInstance(1985, 12, 1);
        insert newAuction;
        insert newContact;
        
        for(Integer i = 0; i < 5; i++) {
            Bid__c newBid = new Bid__c();
            newBid.Contact__c = newContact.Id;
            newBid.Auction__c = newAuction.Id;
            newBid.Price__c = (6 + i);
            insert newBid;
        }
        
        List<Bid__c> retrievedBids = BidHistoryController.getResults(newAuction.Id);
        System.assertEquals(5, retrievedBids.size());
    }
}