Project2/force-app/main/default/objects/Auction__c/Auction__c.object-meta.xml
<CustomObject>
    <label>Auction</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Auction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project2/basePackage/main/default/objects/Auction__c/fields/Auction_Title__c.field-meta.xml
<CustomField>
    <fullName>Auction_Title__c</fullName>
    <label>Auction Title</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project2/WholeProject/basePackage/main/default/objects/Auction__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <label>Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

Project2/WholeProject/basePackage/main/default/objects/Auction__c/fields/Product_Tags__c.field-meta.xml
<CustomField>
    <fullName>Product_Tags__c</fullName>
    <label>Product Tags</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tags</valueSetName>
    </valueSet>
</CustomField>

Project2/force-app/main/default/objects/Bid__c/Bid__c.object-meta.xml
<CustomObject>
    <label>Bid</label>
    <nameField>
        <displayFormat>BID-{0000}</displayFormat>
        <label>Bid ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project2/force-app/main/default/objects/Bid__c/fields/Auction__c.field-meta.xml
<CustomField>
    <fullName>Auction__c</fullName>
    <label>Auction</label>
    <referenceTo>Auction__c</referenceTo>
    <relationshipLabel>Bids</relationshipLabel>
    <relationshipName>Bids</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project2/basePackage/main/default/globalValueSets/Tags.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>Toys &amp; Games</fullName>
    </customValue>
    <customValue>
        <fullName>Art</fullName>
    </customValue>
    <customValue>
        <fullName>Sporting Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Music</fullName>
    </customValue>
    <customValue>
        <fullName>Clothing</fullName>
    </customValue>
    <masterLabel>Tags</masterLabel>
</GlobalValueSet>

Project2/homePage/main/default/classes/featuredSearchHelper.cls
public with sharing class featuredSearchHelper {
	
    @AuraEnabled(cacheable=true)
    public static list<Auction__c> getAuctionList(string searchKey){
        // Generate a usable search key
     	string sTempSearchKey = searchKey;
        Integer count = 0;
        System.debug('searchkey created');
        
        // create auction list to store search results
        list<Auction__c> lstAuction = new list<Auction__c>();
        System.debug('List created');
        
        //query auctions for all matching type records, only grabbing tags for testing
        for(Auction__c auc : [Select Auction_Title__c, Image__c, Product_Tags__c
                           from Auction__c
                            WHERE Product_Tags__c includes (:sTempSearchKey)]){
                                //Only add the first items until the featured list is full, then cycle to only add items with more bids.
                                if(lstAuction.size() <= 5){
                                    lstAuction.add(auc);
                                }
                                // After the list is full, start checking bid sizes.
                                else{
                                    // Count cycles the lstAuction value.
                                    count = 0;
                                    
                                    // For every auction on the List auction, compare the new auction against them. 
                                    // If the new auction has MORE RELATED BIDS than the current one
                                    // replace the currently selected object with the new one.
                                    for(Auction__c auct : lstAuction){
                                    if([SELECT COUNT()
                                       from Bid__c
                                       WHERE Auction__c = :auc.Id] > 
                                       [SELECT COUNT()
                                       FROM Bid__c
                                       WHERE Auction__c = :lstAuction.get(count).Id]){
                                           lstAuction.remove(count);
                                           lstAuction.add(auc);
                                           break;
                                       } 
                                    count++;
                                    }
                                }
                                
                                
                                System.debug('Added an item');
                            }
        

        // Return lstAuction of all featured products.
        System.debug('Returning List');
        return lstAuction;
    }
}