Project2/force-app/main/default/objects/Auction__c/Auction__c.object-meta.xml
<CustomObject>
    <label>Auction</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Auction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project2/basePackage/main/default/objects/Auction__c/fields/Auction_Title__c.field-meta.xml
<CustomField>
    <fullName>Auction_Title__c</fullName>
    <label>Auction Title</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project2/WholeProject/basePackage/main/default/objects/Auction__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <label>Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

Project2/force-app/main/default/objects/Bid__c/Bid__c.object-meta.xml
<CustomObject>
    <label>Bid</label>
    <nameField>
        <displayFormat>BID-{0000}</displayFormat>
        <label>Bid ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project2/force-app/main/default/objects/Bid__c/fields/Auction__c.field-meta.xml
<CustomField>
    <fullName>Auction__c</fullName>
    <label>Auction</label>
    <referenceTo>Auction__c</referenceTo>
    <relationshipLabel>Bids</relationshipLabel>
    <relationshipName>Bids</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project2/basePackage/main/default/objects/Bid__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bids</relationshipLabel>
    <relationshipName>Bids</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project2/basePackage/main/default/objects/Bid__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

UsersPackage/force-app/main/default/classes/ProfileController.cls
public without sharing class ProfileController {
    @AuraEnabled(cacheable=true)
    public static User getUser() {
        User user = [SELECT name, contactId FROM User WHERE Id=:UserInfo.getUserId()];
        return user;
    }
    
	@AuraEnabled(cacheable=true)
    public static Contact getProfile() {
        User user = [SELECT contactId FROM User WHERE Id=:UserInfo.getUserId()];
        Contact contact = [SELECT name, email FROM Contact WHERE Id=:user.ContactId];
        //Contact contact = [SELECT name FROM Contact];
        return contact;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Bid__c> getBids() {
        User user = [SELECT contactId FROM User WHERE Id=:UserInfo.getUserId()];
        Contact contact = [SELECT name FROM Contact WHERE Id=:user.ContactId];
        Bid__c[] bids = [SELECT Auction__c, Auction__r.Auction_Title__c, Auction__r.Image__c, Price__c, Contact__c FROM Bid__c WHERE Contact__c=:contact.Id];
        //Bid__c[] bids = [SELECT Auction__c, Auction__r.Auction_Title__c, Auction__r.Image__c, Price__c, Contact__c FROM Bid__c];
        return bids;
    }
}