Project2/force-app/main/default/objects/Auction__c/Auction__c.object-meta.xml
<CustomObject>
    <label>Auction</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Auction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project2/basePackage/main/default/objects/Auction__c/fields/Auction_Title__c.field-meta.xml
<CustomField>
    <fullName>Auction_Title__c</fullName>
    <label>Auction Title</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project2/WholeProject/basePackage/main/default/objects/Auction__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <label>Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

Project2/force-app/main/default/objects/Auction__c/fields/Shipping_Cost__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Cost__c</fullName>
    <label>Shipping Cost</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Project2/force-app/main/default/objects/Bid__c/Bid__c.object-meta.xml
<CustomObject>
    <label>Bid</label>
    <nameField>
        <displayFormat>BID-{0000}</displayFormat>
        <label>Bid ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project2/force-app/main/default/objects/Bid__c/fields/Auction__c.field-meta.xml
<CustomField>
    <fullName>Auction__c</fullName>
    <label>Auction</label>
    <referenceTo>Auction__c</referenceTo>
    <relationshipLabel>Bids</relationshipLabel>
    <relationshipName>Bids</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project2/basePackage/main/default/objects/Bid__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bids</relationshipLabel>
    <relationshipName>Bids</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project2/basePackage/main/default/objects/Bid__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Project2/force-app/main/default/classes/BuyerController.cls
public without sharing class BuyerController {
	@AuraEnabled(cacheable=true)
    public static List<Object> getBids() {
        Contact customer = ProfileController.getProfile();
        AggregateResult[] customerBids = getCustomerBids(customer);
        List<Id> auctionIds = new List<Id>();
        for (AggregateResult customerBid : customerBids) {
            // Casts the AggregateResult Object to Id
            auctionIds.add((Id) customerBid.get('Auction__c'));
        }
        AggregateResult[] maxBids = getMaxBids(auctionIds);
        
        List<Map<String, Object>> bidsMapList = combineBids(customerBids, maxBids);
        bidsMapList = appendAuctionInfo(bidsMapList);
        System.debug(bidsMapList);
        
        return bidsMapList;
    }
    
    public static List<AggregateResult> getCustomerBids(Contact customer) {
        AggregateResult[] customerBids = [SELECT Auction__c, MAX(Price__c) CustomerBid, MAX(Id) Id
                                  FROM Bid__c WHERE Contact__c=:customer.Id
                                  GROUP By Auction__c];
        return customerBids;
    }
    
    public static List<AggregateResult> getMaxBids(List<Id> AuctionIds) {
        AggregateResult[] maxBids = [SELECT Auction__c, MAX(Price__c) MaxBid, MAX(Contact__c) MaxBid_Contact__c
                                     FROM Bid__c WHERE Auction__c=:auctionIds
                                     GROUP By Auction__c];
        return maxBids;
    }
    
    public static List<Map<String, Object>> combineBids(List<sObject> bidsA, List<sObject> bidsB) {
        if (bidsA.size() == bidsB.size()) {
            List<Map<String, Object>> combinedMaps = new List<Map<String, Object>>();
            for (Integer i = 0; i < bidsA.size(); i++) {
           		sObject bidA = bidsA[i];
                sObject bidB = bidsB[i];
                Map<String, Object> bidAMap = bidA.getPopulatedFieldsAsMap();
                Map<String, Object> bidBMap = bidB.getPopulatedFieldsAsMap();
                
                // New combination map is required, as source maps are read-only
                Map<String, Object> combinedMap = new Map<String, Object>();
                combinedMap.putAll(bidAMap);
                combinedMap.putAll(bidBMap);
                combinedMaps.add(combinedMap);
            }
            return combinedMaps;
        } else {
            return null;
        }
    }
    
    public static List<Map<String, Object>> appendAuctionInfo(List<Map<String, Object>> bidsMapList) {
        List<Id> bidIds = new List<Id>();
        for (Map<String, Object> bidsMap : bidsMapList) {
            Id bidId = (Id) bidsMap.get('Id');
            bidIds.add(bidId);
        }
        List<Bid__c> auctionList = [SELECT Auction__r.Auction_Title__c, Auction__r.Image__c, Auction__r.Shipping_Cost__c, Name FROM Bid__c WHERE Id=:bidIds];
        for (Integer i = 0; i < bidsMapList.size(); i++) {
            Map<String, Object> bidsMap = bidsMapList[i];
            Map<String, Object> auctionMap = auctionList[i].getPopulatedFieldsAsMap();
            bidsMap.putAll(auctionMap);
        }
        return bidsMapList;
    }
}